# Generated by Django 6.0.6 on 2026-06-16 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('tweets_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-tweets_count'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=160)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('avatar', models.ImageField(blank=True, default='avatars/default.png', upload_to='avatars/')),
                ('cover', models.ImageField(blank=True, upload_to='covers/')),
                ('is_verified', models.BooleanField(default=False)),
                ('followers_count', models.IntegerField(default=0)),
                ('following_count', models.IntegerField(default=0)),
                ('tweets_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=280)),
                ('likes_count', models.IntegerField(default=0)),
                ('retweets_count', models.IntegerField(default=0)),
                ('replies_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to=settings.AUTH_USER_MODEL)),
                ('parent_tweet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.tweet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Retweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retweets', to=settings.AUTH_USER_MODEL)),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retweeted_by', to='core.tweet')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_tweets', to=settings.AUTH_USER_MODEL)),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='core.tweet')),
            ],
        ),
        migrations.CreateModel(
            name='TweetHashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='core.hashtag')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtags', to='core.tweet')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['follower'], name='core_follow_followe_986d95_idx'), models.Index(fields=['following'], name='core_follow_followi_a11b6b_idx')],
                'unique_together': {('follower', 'following')},
            },
        ),
        migrations.AddIndex(
            model_name='tweet',
            index=models.Index(fields=['-created_at'], name='core_tweet_created_59ac93_idx'),
        ),
        migrations.AddIndex(
            model_name='tweet',
            index=models.Index(fields=['author'], name='core_tweet_author__1b0b49_idx'),
        ),
        migrations.AddIndex(
            model_name='tweet',
            index=models.Index(fields=['parent_tweet'], name='core_tweet_parent__ff5c5d_idx'),
        ),
        migrations.AddIndex(
            model_name='retweet',
            index=models.Index(fields=['user'], name='core_retwee_user_id_cc598e_idx'),
        ),
        migrations.AddIndex(
            model_name='retweet',
            index=models.Index(fields=['tweet'], name='core_retwee_tweet_i_7f1dfe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='retweet',
            unique_together={('user', 'tweet')},
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['user'], name='core_like_user_id_a989fd_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['tweet'], name='core_like_tweet_i_2e9942_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'tweet')},
        ),
        migrations.AddIndex(
            model_name='tweethashtag',
            index=models.Index(fields=['tweet'], name='core_tweeth_tweet_i_3e47be_idx'),
        ),
        migrations.AddIndex(
            model_name='tweethashtag',
            index=models.Index(fields=['hashtag'], name='core_tweeth_hashtag_91ae5f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tweethashtag',
            unique_together={('tweet', 'hashtag')},
        ),
    ]
