from django.urls import path
from .views import (
    TimelineView,
    ProfileView,
    TweetDetailView,
    post_tweet,
    like_tweet,
    unlike_tweet,
    retweet,
    unretweet,
    reply_tweet,
    follow_user,
    unfollow_user,
    notifications,
    trending,
    bookmarks,
    bookmark_tweet,
    unbookmark_tweet,
    messages,
    message_thread,
    new_message,
)

urlpatterns = [
    path('', TimelineView.as_view(), name='timeline'),
    path('notifications/', notifications, name='notifications'),
    path('trending/', trending, name='trending'),
    path('bookmarks/', bookmarks, name='bookmarks'),
    path('messages/', messages, name='messages'),
    path('messages/new/', new_message, name='new-message'),
    path('messages/<username>/', message_thread, name='message-thread'),
    path('@<username>/', ProfileView.as_view(), name='profile'),
    path('tweet/<int:pk>/', TweetDetailView.as_view(), name='tweet-detail'),
    path('tweet/post/', post_tweet, name='post-tweet'),
    path('tweet/<int:tweet_id>/like/', like_tweet, name='like-tweet'),
    path('tweet/<int:tweet_id>/unlike/', unlike_tweet, name='unlike-tweet'),
    path('tweet/<int:tweet_id>/retweet/', retweet, name='retweet'),
    path('tweet/<int:tweet_id>/unretweet/', unretweet, name='unretweet'),
    path('tweet/<int:tweet_id>/reply/', reply_tweet, name='reply-tweet'),
    path('tweet/<int:tweet_id>/bookmark/', bookmark_tweet, name='bookmark-tweet'),
    path('tweet/<int:tweet_id>/unbookmark/', unbookmark_tweet, name='unbookmark-tweet'),
    path('@<username>/follow/', follow_user, name='follow-user'),
    path('@<username>/unfollow/', unfollow_user, name='unfollow-user'),
]
